export default {
  apiEndPoints: {
    getSignup: '/api/user/signUp',
    getLogin: '/api/user/login',
    getOtp: '/api/user/verifyUser',
    getVendorInfo: '/api/vendor/vendorinfo',
    getGeneralInfo: '/api/vendor/generalinfo',
    getVendorList: '/api/admin/vendorApplications',
    getVendorStatus: '/api/admin/applicationApproval',
    // getThriftVendorInfo: '/api/vendor/getApprovedVendorInfo',
    getStoreInfo: '/api/vendor/getEstoreInfo',
    getThriftCategory: '/api/vendor/getCategories',
    getThriftAddProduct: '/api/vendor/addProduct',
    getThriftDetails: '/api/staticContentRouter/getProducts',
    getStoreInfoUpdate: '/api/vendor/estoreInfo',
    getProductInfo: '/api/staticContentRouter/getProductInfo',
    getThriftStoreInfo: '/api/staticContentRouter/getStoreInfo',
    getAddCart: '/api/user/addToCart',
    getCart: '/api/user/getCart',
    getCheckout: '/api/user/completePayment',
    getAddStore: '/api/vendor/createEstore',
    getVendorCompanyDetails: '/api/vendor/getEstores',
    getProductMessage: '/api/user/userProductEnquiry',
    getPaymentStatus: '/api/user/paymentStatus',
    getResetPassword: '/api/user/forgotPassword',
    getUpdatePassword: '/api/user/resetPassword ',
    getListYourAds: '/api/user/advt/uploadAds',
    getYourAds: '/api/staticContentRouter/getAds',
    getProfile: '/api/vendor/vendorInfo',
    getProductList: '/api/vendor/product',
    getUserList: '/api/admin/users',
  },

  apiBaseUrl: {
    dev: 'https://stagingbe.insta-kart.com',
    prod: 'https://backend.insta-kart.com',
  },
};
